version: "3.7"

services:
  shop:
    container_name: shop
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - .:/app/
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 8005:8005
    links:
      - db
    depends_on:
      - db
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"


  db:
    container_name: shop_db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - 5435:5432

  celery_worker:
    command:  celery
    container_name: celery_worker
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - shop
      - db
      - rabbit
    restart: always
    hostname: celery_worker

  celery_beat:
    command: beat
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: celery_beat
    depends_on:
      - shop
      - db
      - rabbit
    hostname: celery_beat
    restart: always

volumes:
  postgres-data:
  rabbitmq_data:
